### ISSUE TITLE
Please update readme

### ISSUE THREAD

**Issue by JeanAzzopardi** [twelve17/openalpr-ios#3]
I think the readme hasn't been updated in a while.

E.g. this instruction: # ./bin/sync_openalpr_source.sh ~/work/lp/openalpr

Is invalid as there are now 2 scripts in the bin directory which handle the syncing.

**Comment by steffex** [comment]
In case somebody is looking for a way to get the latest version (at time of writing bcfd8459fc4e1edcbcc3c4f3c75c0d3e66c3c330) working, use these steps below:

1. clone openalpr in your downloads folder with folder (or somewhere else, but then also change step 3)
2. clone this repo somewhere
3. edit the file `bin/sync_from_openalpr_source.sh` and change line 6 to: `OPENALPR_SRC_DIR="$HOME/Downloads/openalpr"`
4. also change line 61 to: `mkdir -p $INCLUDE_DIR` (otherwise the sync script will fail)
5. save and close `bin/sync_from_openalpr_source.sh`.
6. run `./bin/sync_from_openalpr_source.sh` from this repo's root
7. run `./bin/build_dependencies.sh`
8. it works! :+1:

**Comment by twelve17** [comment]
Hi @steffex, 

Thanks for your feedback and sorry for the delay!  

For v2 of this project, I have replaced the old instructions and bash scripts with a Ruby script to build the OpenALPR and dependency Frameworks, as well as the OpenALPR Xcode project.  A sample app is included.  These changes have been pushed to the master branch, and the old version has been moved to branch `1_0`.  Feel free to check out this new script and see if it works for you.  I will no longer be working on or supporting the `1_0` codebase.
